
        
name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install Linux dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git \
            zip \
            unzip \
            autoconf \
            automake \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libtinfo6 \
            cmake \
            libffi-dev \
            libssl-dev \
            autopoint \
            gettext

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK packages
        run: |
          yes | sdkmanager --licenses || true

          sdkmanager "platform-tools"
          sdkmanager "platforms;android-35"
          sdkmanager "build-tools;35.0.0"
          sdkmanager "build-tools;37.0.0"

          yes | sdkmanager --licenses || true

      - name: Verify Android SDK
        run: |
          echo "ANDROID_HOME=$ANDROID_HOME"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"

          sdkmanager --list_installed

          test -f "$ANDROID_HOME/platform-tools/adb"
          test -f "$ANDROID_HOME/platforms/android-35/android.jar"
          test -f "$ANDROID_HOME/build-tools/37.0.0/aidl"

          echo "Android SDK is ready!"

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          python -m pip install buildozer cython
      - name: Connect Buildozer to Android SDK
        run: |
          echo "ANDROID_HOME=$ANDROID_HOME"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
          buildozer android clean || true
          sed -i "s|^#android.sdk_path =.*|android.sdk_path = $ANDROID_HOME|" buildozer.spec
          sed -i "s|^android.sdk_path =.*|android.sdk_path = $ANDROID_HOME|" buildozer.spec
          grep "android.sdk_path" buildozer.spec
      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Favaran-Record-APK
          path: bin/*.apk
